import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Guides / tutorial sidebar (existing - untouched)
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],

  // API Reference sidebar - auto-generated from docs/api/ directory
  apiSidebar: [
    'api/intro',
    {
      type: 'category',
      label: 'Authentication',
      items: ['api/auth', 'api/devices'],
    },
    {
      type: 'category',
      label: 'QR & Stock',
      items: ['api/qr', 'api/stock', 'api/stock-analytics', 'api/scans'],
    },
    {
      type: 'category',
      label: 'Users & Access',
      items: ['api/users', 'api/privileges'],
    },
    {
      type: 'category',
      label: 'Master Data',
      items: ['api/master-data', 'api/tasks'],
    },
    'api/health',
  ],
};

export default sidebars;
